import = ["~/.config/alacritty-theme/themes/iterm.toml"]
# import = ["~/.config/alacritty-theme/themes/baitong.toml"]

[[keyboard.bindings]]
key = 0
mods = "Alt"

[keyboard.bindings.command]
args = ["-e", "vttest"]
program = "alacritty"

[window]
# decorations = "none"
# gtk_theme_variant = "none"
opacity = 0.77
# opacity = 1.00

[window.padding]
x = 5
y = 5
